# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - npm run build:webview
    silent: true
  install:
    cmds:
      - npm run install:all
    silent: true
  "lint:fix":
    cmds:
      - npm run lint:fix
    silent: true
  test:
    cmds:
      - npm run compile
      - node ./out/test/runTest.js
    silent: true
