# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - npm run build:webview
    silent: true
  install:
    cmds:
      - npm run install:all
    silent: true
